export class RefCareAndSupport {
    constructor(
      public abuseNeglectedSw: string,
      public adltProtectSrvcSw: string,
      public anotherCareGiverSw: string,
      public anotherPlaceSw: string,
      public age: number,
      public behNoneSw: string,
      public behSrvcsSw: string,
      public cargvrBirthDt,
      public cargvrDiedSw: string,
      public cargvrName: string,
      public cargvrReltshpCd: string,
      public childProtectSrvcSw: string,
      public cleaningDressSw: string,
      public toiletingSw: string,
      public criminalJusticeSw: string,
      public eatingSw: string,
      public goodDcsnSafeSw: string,
      public knowFamilySw: string,
      public medicinesSw: string,
      public mentalHlthCrisisSw: string,
      public noneOfAboveSw: string,
      public prsnHelpNoneSw: string,
      public phyclHurtBehSw: string,
      public primaryCargvrSw: string,
      public cargvrDisableSw: string,
      public cargvrPoorHlthSw: string,
      public psychiatricHospitalSw: string,
      public residentialTrtmntSw : string,
      public tellingOthrsSw: string,
      public personId: string,
      public transferBedChairSw: string,
      public understandInstructionSw: string,
      public walkWheelchairSw: string,
      public reqPageId: string,
      public refId: string,
    ) { }
}
