export class RefEmergentCircumstancesReview {
    constructor(
        public reqPageId: string,
        public abuseCurrLivSw: string,
        public adaptBehLsaResSw: string,
        public addCurrEmrgTxt: string,
        public adltTrnstnCustdySw: string,
        public anticipateChngSupTxt: string,
        public behHlthCrisisPrevSw: string,
        public caregvrPermIncapSw: string,
        public cargvrRecentIncapSw: string,
        public criticalCircumTxt: string,
        public currTreatBehCondTxt: string,
        public electronicSignature: string,
        public enrolEcfTranLongSw: string,
        public howPrsnIsSupTxt: string,
        public intakeAssessorObservTxt: string,
        public justification: string,
        public legalDocsSw: string,
        public optTriedNotWorkTxt: string,
        public othrDesc: string,
        public othrSupAvailTxt: string,
        public othrSw: string,
        public ovr21AdltEnrolEcfSw: string,
        public phyclClinicalNoteSw: string,
        public rcntEvntCurCircuTxt: string,
        public srvcUrgntNeededSw: string,
        public supNeededTxt: string,
        public verifTrgtPoplationSw: string,
        public intakeOutcomeId: string
    ) { }
}
